<?php

/**
 * Saves all SSS Registration sections into multiple tables.
 * Uses a Transaction to ensure "All or Nothing" data integrity.
 */
function saveSSSRegistration(PDO $pdo, array $data): bool {
    try {
        $pdo->beginTransaction();

        // --- 1. PERSONAL DATA (The Parent Record) ---
        $sqlA = "INSERT INTO personal_data (lastname, firstname, middlename, suffix, dob, gender, civilstatus, civil_status_reason, tax_number, nationality, religion, pob_city, pob_country, home_address, mobile, email) 
                 VALUES (:lastname, :firstname, :middlename, :suffix, :dob, :gender, :civilstatus, :civil_reason, :tax, :nat, :rel, :pob_city, :pob_country, :address, :mobile, :email)";
        
        $stmtA = $pdo->prepare($sqlA);
        $stmtA->execute([
            ':lastname'    => $data['lastname'],
            ':firstname'   => $data['firstname'],
            ':middlename'  => $data['middlename'] ?? '',
            ':suffix'      => $data['suffix'] ?? '',
            ':dob'         => $data['dateofbirth'],
            ':gender'      => $data['gender'] ?? '',
            ':civilstatus' => $data['civilstatus'] ?? '',
            ':civil_reason'=> $data['reasonforother'] ?? '',
            ':tax'         => $data['taxnumber'] ?? '',
            ':nat'         => $data['nationality'],
            ':rel'         => $data['religion'] ?? '',
            ':pob_city'    => $data['city&province'] ?? '',
            ':pob_country' => $data['city&country'] ?? '',
            ':address'     => $data['final_address'],
            ':mobile'      => $data['mobilenumber'],
            ':email'       => $data['emailaddress']
        ]);

        // Get the ID generated by the insert above
        $lastId = $pdo->lastInsertId();

        // --- 2. BENEFICIARIES DATA ---
        $childrenStr = "";
        for ($i = 1; $i <= 5; $i++) {
            $fname = trim($data["childfirstname$i"] ?? '');
            $lname = trim($data["childlastname$i"] ?? '');
            // Only add if both names are provided
            if (!empty($fname) && !empty($lname)) {
                $childrenStr .= "Child $i: $fname $lname; ";
            }
        }
        $other_bene = trim(($data['otherfirstname1'] ?? '') . " " . ($data['otherlastname1'] ?? '')) . " (" . ($data['otherrelationship1'] ?? 'N/A') . ")";

        $sqlB = "INSERT INTO beneficiaries_data (reg_id, children_info, other_beneficiaries) VALUES (?, ?, ?)";
        $pdo->prepare($sqlB)->execute([$lastId, $childrenStr, $other_bene]);

        // --- 3. EMPLOYMENT DATA ---
        $empType = !empty($data['monthearn']) ? 'OFW' : 'Self-Employed';
        $earnings = !empty($data['monthlyearning']) ? $data['monthlyearning'] : ($data['monthearn'] ?? '0');
        
        $sqlC = "INSERT INTO employment_certification (reg_id, monthly_earnings, profession, employment_type, cert_date) VALUES (?, ?, ?, ?, ?)";
        $pdo->prepare($sqlC)->execute([
            $lastId,
            $earnings,
            $data['profession/business'] ?? 'N/A',
            $empType,
            $data['Ddate'] ?? date('Y-m-d')
        ]);

        // --- 4. SSS INTERNAL DATA ---
        $sqlD = "INSERT INTO sss_internal_data (reg_id, ss_number, business_code, msc_amount, processed_by) VALUES (?, ?, ?, ?, ?)";
        $pdo->prepare($sqlD)->execute([
            $lastId,
            $data['SSSno'] ?? '',
            $data['businesscode'] ?? '',
            $data['approvedmsc'] ?? '0',
            "SSS System" 
        ]);

        // --- 5. FAMILY DATA ---
        $sqlE = "INSERT INTO family_data (reg_id, father_name, mother_name, spouse_name) VALUES (?, ?, ?, ?)";
        $pdo->prepare($sqlE)->execute([
            $lastId,
            trim(($data['fatherfirstname'] ?? '') . " " . ($data['fatherlname'] ?? '')),
            trim(($data['motherfname'] ?? '') . " " . ($data['motherlname'] ?? '')),
            trim(($data['spousefirstname'] ?? '') . " " . ($data['spouselname'] ?? ''))
        ]);

        // If we reached here without errors, save everything to the DB
        $pdo->commit();
        return true;

    } catch (Exception $e) {
        // If anything fails, undo everything to keep DB clean
        $pdo->rollBack();
        error_log("Registration Error: " . $e->getMessage());
        return false;
    }
}